apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttdfs
  template:
    metadata:
      labels:
        app: ttdfs
    spec:
      containers:
      - image: okteto.dev/ttdfs:latest
        name: ttdfs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "fd6e4b2e-437e-44cb-b0ef-cc3f15dc82a2"
        - name: Vless_Path
          value: "/vl5er355"
        - name: Vmess_UUID
          value: "fd6e4b2e-437e-44cb-b0ef-cc3f15dc82a2"
        - name: Vmess_Path
          value: "/vm66rt6"
        - name: Share_Path
          value: "/v2link"
